### BUILD (Compilazione) ### 

# Uso l'immagine Go standard (Debian based) (alpine mi dava problemi nella correzione)
FROM golang:1.19

# Imposto la cartella di lavoro dentro il container
WORKDIR /app

# Abilito CGO per far funzionare SQLite (go-sqlite3 richiede librerie C)
ENV CGO_ENABLED=1

# Copio i file delle dipendenze
COPY go.mod go.sum ./

# Scarico le Dipendenze
RUN go mod download

# Copio tutto il codice sorgente del backend
COPY . .

# COMPILO il progetto chiamandolo "webapi"
RUN go build -o webapi ./cmd/webapi

# Do i permessi di esecuzione --> Permessi di esecuzione espliciti (per evitare il "permission denied" correzione precedente)
RUN chmod +x webapi

# Creo le cartelle per le immagini 
RUN mkdir -p images/media images/avatars

# Espongo la porta
EXPOSE 3000

# Avvio l'eseguibile
CMD ["./webapi"]