### BUILD (Node.js) ###
FROM node:20 AS build-stage

# Imposto la cartella di lavoro
WORKDIR /app

# Abilito Corepack perché uso Yarn 4.5.0
RUN corepack enable

# Copio Tutto il codice sorgente del frontend, prima di installare
COPY webui/ .

# Installo le dipendenze usando Yarn
RUN yarn install

# Chiamo lo script "build-prod" che è quello che ho nel mio package.json
RUN yarn run build-prod


# ---------------------------------------------------------------------------------------------

### PRODUCTION (Nginx) -> Stage 2 ###
FROM nginx:stable-alpine as production-stage

# Copio i file compilati dalla cartella dist
COPY --from=build-stage /app/dist /usr/share/nginx/html

# Espongo la porta 80 (standard HTTP)
EXPOSE 80

# Avvio Nginx
CMD ["nginx", "-g", "daemon off;"]