### BUILD (Node.js) ###
FROM node:lts as build-stage

# Imposto la cartella di lavoro
WORKDIR /app

# Copio "package.json" Dalla cartella webui --> perché il Dockerfile è nella root, ma il frontend è in webui/
COPY webui/package*.json ./

# Installo le dipendenze
RUN npm install

# Copiamo il codice sorgente del frontend
COPY webui/ .

# Compilo per la Produzione
RUN npm run build

# ---------------------------------------------------------------------------------------------

### PRODUCTION (Nginx) ###
FROM nginx:stable-alpine as production-stage

# Copio i file compilati dallo stage 1 nella cartella di Nginx
COPY --from=build-stage /app/dist /usr/share/nginx/html

# Espongo la porta 80 (standard HTTP)
EXPOSE 80

# Avvio Nginx
CMD ["nginx", "-g", "daemon off;"]