### BUILD (Node.js) ###
FROM node:lts-alpine as frontend-build-stage

# Imposto la cartella di lavoro
WORKDIR /app

# Copio "package.json" Dalla cartella webui --> perché il Dockerfile è nella root, ma il frontend è in webui/
COPY webui/package*.json ./

# Installo le dipendenze
RUN npm install

# Copiamo il codice sorgente del frontend
COPY webui/ .

# Compilo per la Produzione --> (crea la cartella /app/dist)
RUN npm run build

# ---------------------------------------------------------------------------------------------

### PRODUCTION (Nginx) ###
FROM nginx:stable-alpine as front-production-stage

# Copio i file compilati dallo stage 1 alla cartella pubblica di Nginx
COPY --from=frontend-build-stage /app/dist /usr/share/nginx/html

# Espongo la porta 80 (standard HTTP)
EXPOSE 80

# Avvio Nginx
CMD ["nginx", "-g", "daemon off;"]