### BUILD (Compilazione) ### 

# Uso l'immagine Go standard (Debian based) (alpine mi dava problemi nella correzione)
FROM golang:1.20

# Imposto la cartella di lavoro dentro il container
WORKDIR /app

# Copio i file delle dipendenze
COPY go.mod go.sum ./

# Scarico le Dipendenze
RUN go mod download

# Copio tutto il codice sorgente del backend
COPY . .

# Compilo il progetto
RUN go build -o webapi ./cmd/webapi

# Creo le cartelle per le immagini 
RUN mkdir -p images/media images/avatars

# Espongo la porta
EXPOSE 3000

# Avvio l'eseguibile
CMD ["./webapi"]